repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff-check
        name: ruff (ch03/single_model_study)
        files: ^ch03/single_model_study/
        args: [--fix]
      - id: ruff-check
        name: ruff (ch03/multi_model_study)
        files: ^ch03/multi_model_study/
        args: [--fix]
      - id: ruff-format
        name: ruff-format (ch03/multi_model_study)
        files: ^ch03/multi_model_study/
      - id: ruff-check
        name: ruff (ch04/basic_rag_study)
        files: ^ch04/basic_rag_study/
        args: [--fix]
